# SPDX-License-Identifier: GPL-2.0

ccflags-$(CONFIG_IIO_ST_LIS2DW12_STORE_SAMPLE_FIFO_SUSPEND) += -DCONFIG_IIO_ST_LIS2DW12_STORE_SAMPLE_FIFO_SUSPEND

st_lis2dw12-y:= st_lis2dw12_core.o st_lis2dw12_buffer.o st_lis2dw12_events.o

obj-$(CONFIG_IIO_ST_LIS2DW12) += st_lis2dw12.o
obj-$(CONFIG_IIO_ST_LIS2DW12_I2C) += st_lis2dw12_i2c.o
obj-$(CONFIG_IIO_ST_LIS2DW12_SPI) += st_lis2dw12_spi.o
