# SPDX-License-Identifier: GPL-2.0-only

ccflags-$(CONFIG_IIO_ST_ISM330DHCX_ASYNC_HW_TIMESTAMP) += -DCONFIG_IIO_ST_ISM330DHCX_ASYNC_HW_TIMESTAMP
ccflags-$(CONFIG_IIO_ST_ISM330DHCX_MLC_PRELOAD) += -DCONFIG_IIO_ST_ISM330DHCX_MLC_PRELOAD

st_ism330dhcx-y := st_ism330dhcx_core.o st_ism330dhcx_buffer.o \
		   st_ism330dhcx_shub.o st_ism330dhcx_events.o \
		   st_ism330dhcx_mlc.o \
		   st_ism330dhcx_embfunc.o

st_ism330dhcx-$(CONFIG_IIO_ST_ISM330DHCX_ASYNC_HW_TIMESTAMP) += st_ism330dhcx_hwtimestamp.o

obj-$(CONFIG_IIO_ST_ISM330DHCX) += st_ism330dhcx.o
obj-$(CONFIG_IIO_ST_ISM330DHCX_I2C) += st_ism330dhcx_i2c.o
obj-$(CONFIG_IIO_ST_ISM330DHCX_SPI) += st_ism330dhcx_spi.o
