# SPDX-License-Identifier: GPL-2.0

st_ism303dac_accel-y += st_ism303dac_accel_core.o st_ism303dac_accel_buffer.o \
	st_ism303dac_accel_trigger.o

obj-$(CONFIG_IIO_ST_ISM303DAC_ACCEL) += st_ism303dac_accel.o
obj-$(CONFIG_IIO_ST_ISM303DAC_ACCEL_I2C) += st_ism303dac_accel_i2c.o
obj-$(CONFIG_IIO_ST_ISM303DAC_ACCEL_SPI) += st_ism303dac_accel_spi.o
