# SPDX-License-Identifier: GPL-2.0

st_mag40-y += st_mag40_buffer.o st_mag40_core.o
obj-$(CONFIG_ST_MAG40_IIO) += st_mag40.o
obj-$(CONFIG_ST_MAG40_I2C_IIO) += st_mag40_i2c.o
obj-$(CONFIG_ST_MAG40_SPI_IIO) += st_mag40_spi.o
