# SPDX-License-Identifier: GPL-2.0

st_h3lis331dl-y := st_h3lis331dl_core.o st_h3lis331dl_buffer.o

obj-$(CONFIG_IIO_ST_H3LIS331DL) += st_h3lis331dl.o
obj-$(CONFIG_IIO_ST_H3LIS331DL_I2C) += st_h3lis331dl_i2c.o
obj-$(CONFIG_IIO_ST_H3LIS331DL_SPI) += st_h3lis331dl_spi.o
