# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_ST_LPS22HB_IIO) += st_lps22hb.o
obj-$(CONFIG_ST_LPS22HB_I2C_IIO) += st_lps22hb_i2c.o
obj-$(CONFIG_ST_LPS22HB_SPI_IIO) += st_lps22hb_spi.o

st_lps22hb-y += st_lps22hb_core.o st_lps22hb_buffer.o
