# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_ST_LPS22HH_IIO) += st_lps22hh.o
obj-$(CONFIG_ST_LPS22HH_I2C_IIO) += st_lps22hh_i2c.o
obj-$(CONFIG_ST_LPS22HH_SPI_IIO) += st_lps22hh_spi.o

st_lps22hh-y += st_lps22hh_core.o st_lps22hh_buffer.o
