# SPDX-License-Identifier: GPL-2.0

st_mag3d-y += st_mag3d_core.o st_mag3d_buffer.o
obj-$(CONFIG_ST_MAG3D_IIO) += st_mag3d.o
obj-$(CONFIG_ST_MAG3D_I2C_IIO) += st_mag3d_i2c.o
obj-$(CONFIG_ST_MAG3D_SPI_IIO) += st_mag3d_spi.o
